catalog/urls.py
from django.urls import path,include
from . import views


urlpatterns = [

    path('',views.index, name = 'index' ),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedListView.as_view(), name='all-borrowed'),
    path('books/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('authors/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('authors/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('authors/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('books/create/', views.BookCreate.as_view(), name='book-create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),

]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('',RedirectView.as_view(url = '/catalog/',permanent  =True)),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse  # To generate URLS by reversing URL patterns
from django.contrib.auth.models import User

import uuid  # Required for unique book instances
from datetime import date



class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
        )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title



class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)
# Create your models here.

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as ugly
import datetime
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date"
                                             " between now and 4 weeks (default 3).",input_formats=['%d %m %Y','%d.%m.%Y','%Y-%m-%d' ])
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Проверка того, что дата не выходит за "нижнюю" границу(не в прошлом).
        if data < datetime.date.today():
            raise ValidationError(ugly('Invalid date: renewal in past'))
            #Проверка того, то дата не выходит за "верхнюю" границу (+4недели).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(ugly('Invalid date: renewal more than 4 weeks ahead'))
                # Помните, что всегда надо возвращать "очищенные" данные.
        return data

catalog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import generic
from .models import Book, Author, Genre, BookInstance
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import RenewBookForm
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.views.generic.edit import CreateView, UpdateView,DeleteView
import datetime

def index(req):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_authors = Author.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status='a').count()
    word_b = 'Гарри'
    word_g = 'По'

    num_books_word = Book.objects.filter(title__icontains=word_b).count()
    num_genres_word = Genre.objects.filter(name__icontains=word_g).count()
    num_visits = req.session.get('num_visits', 0)
    req.session['num_visits'] = num_visits + 1


    return render(req, 'index/index.html', locals())

class BookListView(generic.ListView):
    model = Book
    template_name = 'catalog/book_list.html'
    paginate_by = 5

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'catalog/book_detail.html'
class AuthorListView(generic.ListView):
    model = Author
    template_name = 'catalog/author_list.html'
    paginate_by = 5

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'catalog/author_detail.html'

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 3
    def get_queryset(self):

        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
# Create your views here.
class BorrowedListView(UserPassesTestMixin,generic.ListView):
    model = BookInstance
    template_name = 'catalog/all_borrowed_books.html'
    paginate_by = 5
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')
    def test_func(self):
        return self.request.user.is_staff



@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request,pk):
    bookinst = get_object_or_404(BookInstance, pk=pk)

    # Если данный запрос типа POST, тогда
    if request.method == 'POST':
        # Создаем экземпляр формы и заполняем данными из запроса(связывание, binding):
        form = RenewBookForm(request.POST)
        # Проверка валидности данных формы:
        if form.is_valid():
            # Обработка данных из form.cleaned_data
            # (здесь мы просто присваиваем их полю due_back)
            bookinst.due_back = form.cleaned_data['renewal_date']
            bookinst.save()
            # Переход по адресу 'all-borrowed':
            return HttpResponseRedirect(reverse('all-borrowed'))
    # Если это GET (или какой-либо еще), создать форму по умолчанию.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date':
                                      proposed_renewal_date, })
    return render(request, 'catalog/book_renew_librarian.html', locals())

class AuthorCreate(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('authors')
    initial={'date_of_death':'12/10/2016',}
    def test_func(self):
        return self.request.user.is_staff
    def handle_no_permission(self):
        return HttpResponseRedirect(reverse('login')+'?next=/catalog/authors/create/')

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
class BookCreate(CreateView):
    model = Book
    fields = '__all__'

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

catalog/templates/catalog/all_borrowed_books.html
{% extends "index/base_generic.html" %}
{% block content %}

{% if user.is_staff %}
    <h1>All borrowed books</h1>
    {% if bookinstance_list %}
        <ul>
        {% for bookinst in bookinstance_list %}
            <li style="{% if bookinst.is_overdue %}color:red{% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk%}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) -  {{ bookinst.borrower }} {% if perms.catalog.can_mark_returned %}  <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
            {% endif %}
            </li>

        {% endfor %}
        </ul>
    {% else %}
    <p>There are no books borrowed.</p>
    {% endif %}
{% else %}
    YOU DONT HAVE PERMISSION
{% endif %}

{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends "index/base_generic.html" %}
{% block content %}
<h1>Delete Author</h1>
<p>Are you sure you want to delete the author: {{ author }}?</p>
<form action="" method="POST">
{% csrf_token %}
    <input type="submit" value="Yes, delete." />
</form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "index/base_generic.html" %}
{% block content %}
<h1>Author: {{ author.first_name }} {{ author.last_name }}</h1>
    {% if user.is_staff %}
<div class="row" style="padding-left: 20px">
    <a href="{% url 'author-update' author.pk %} " class="btn btn-info">Update</a>
    <a href="{% url 'author-delete' author.pk%}" class="btn" >Delete </a>
</div>
    {% endif %}
<div style="margin-left:20px;margin-top:40px">
<h4>Books</h4> {% for book in author.book_set.all %}
    <hr>
    <p><a href = '{{ book.get_absolute_url }}'>{{ book }}</a> {% if not forloop.last %} {% endif %}

    <p style="margin-left: 10px ">{{ book.summary }}</p></p>
{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "index/base_generic.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "index/base_generic.html" %}
{% block content %}
    <div class="row">
        <div class="col-sm-3 col-xs-5"><h1>Author List</h1></div>
        {% if user.is_staff %}
        <a href="{%url 'author-create'  %}  " class="btn btn-info" style="margin-top:20px ">Add New Author</a>
        {% endif %}
    </div>

{% if author_list %}
<ul>
{% for auth in author_list %}
<li>
<a href="{{ auth.get_absolute_url }}">{{ auth.last_name }} {{ auth.first_name}}  </a>

</li>
{% endfor %}
</ul>

{% else %}
<p>There are no authors in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "index/base_generic.html" %}
{% block content %}
<h1>Delete Book</h1>
<p>Are you sure you want to delete the book: {{ book }}?</p>
<form action="" method="POST">
{% csrf_token %}
    <input type="submit" value="Yes, delete." />
</form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "index/base_generic.html" %}
{% block content %}
<h1>Title: {{ book.title }}</h1>


<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!--
author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {% for genre in book.genre.all %}
{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            {% if user.is_staff %}
<div class="row" style="padding-left: 15px">
    <a href="{% url 'book-update' book.pk %} " class="btn btn-info">Update</a>
    <a href="{% url 'book-delete' book.pk%}" class="btn" >Delete </a>
</div>
    {% endif %}
<div style="margin-left:20px;margin-top:20px">
<h4>Copies</h4>
{% for copy in book.bookinstance_set.all %}
<hr>
<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd'%}text-danger{%else%}text-warning{% endif %}">{{ copy.get_status_display }}</p>
{% if copy.status != 'a' %}<p><strong>Due to be returned:</strong>
{{copy.due_back}}</p>{% endif %}
<p><strong>Imprint:</strong> {{copy.imprint}}</p>
<p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "index/base_generic.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "index/base_generic.html" %}
{% block content %}
    <div class="row">
        <div class="col-sm-3 col-xs-5"><h1>Book List</h1></div>
        {% if user.is_staff %}
        <a href="{%url 'book-create'  %}  " class="btn btn-info" style="margin-top:20px ">Add New Book</a>
        {% endif %}
    </div>
{% if book_list %}
<ul>
{% for book in book_list %}
<li>
<a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
({{book.author}})
</li>
{% endfor %}
</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "index/base_generic.html" %}
{% block content %}
   {% if perms.catalog.can_mark_returned %}
    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due
    date: {{bookinst.due_back}}</p>
    <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form }}

    </table>
    <input type="submit" value="Submit" />
    </form>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "index/base_generic.html" %}
{% block content %}
<h1>Borrowed books</h1>
{% if bookinstance_list %}
<ul>
{% for bookinst in bookinstance_list %}
<li style="{% if bookinst.is_overdue %}color:red{% endif %}">
<a href="{% url 'book-detail' bookinst.book.pk%}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
</li>
{% endfor %}
</ul>
{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}